# Generated by Django 5.2.5 on 2025-08-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20231120_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_dead',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
